OBTW
	Recursive fibonacci
	Written in LOLCODE
TLDR
HAI 1.2

	HOW IZ I fib YR n
		BTW n <= 1
		BOTH SAEM n AN SMALLR OF n AN 1, O RLY?
			YA RLY
				FOUND YR n
			NO WAI
				FOUND YR SUM OF I IZ ME'Z fib YR DIFF OF n AN 1 MKAY AN I IZ ME'Z fib YR DIFF OF n AN 2 MKAY
		OIC
	IF U SAY SO

	VISIBLE I IZ fib YR 10 MKAY
KTHXBYE